const defaultPlan = [
  {
    id: "dia-1",
    name: "Dia 1 - Perna",
    focus: "Quadriceps",
    goal: "Agachamento, unilateral, extensora e controle de amplitude.",
    exercises: [
      ex(
        "Mobilidade tornozelo",
        "2",
        "15 por lado",
        "15-30 seg",
        "Apenas destravar. Nao transformar em aquecimento longo.",
      ),
      ex(
        "Extensora no banco - ativacao",
        "3",
        "15 a 20",
        "45-60 seg",
        "1 seg de contracao no topo. Descida controlada. Sem chutar o peso.",
      ),
      ex(
        "Agachamento livre com barra",
        "4",
        "6 a 10",
        "2 min",
        "Principal. Barra alta, tronco mais vertical, joelho avancando e pe inteiro no chao. Usar suporte de seguranca. Manter 1-2 RIR.",
      ),
      ex(
        "Agachamento bulgaro foco quadriceps",
        "3-4",
        "8 a 12 por perna",
        "90 seg",
        "Tronco mais em pe, pe da frente nao muito longe, amplitude grande.",
      ),
      ex(
        "Agachamento ciclista com calcanhar elevado",
        "3",
        "10 a 15",
        "90 seg",
        "Calcanhar em anilha ou step estavel. 3 seg descendo, pausa curta no fundo e sobe forte.",
      ),
      ex(
        "Extensora no banco - finalizadora",
        "3",
        "10 a 15",
        "60 seg",
        "Ultima serie: 10-15 reps + 15 seg descanso + 5-8 reps. Contracao limpa.",
      ),
      ex(
        "Panturrilha em pe no step",
        "4",
        "10 a 20",
        "45-60 seg",
        "Amplitude total. Desce tudo, sobe tudo e segura 1 seg no topo.",
      ),
      ex(
        "Abdutora no cross/caneleira",
        "2",
        "15 a 20 por lado",
        "45-60 seg",
        "Opcional. So entra se sobrar energia.",
      ),
    ],
  },
  {
    id: "dia-2",
    name: "Dia 2 - Costas",
    focus: "Costas completa",
    goal: "Costas largas e densas, sem transformar tudo em biceps.",
    exercises: [
      ex(
        "Mobilidade escapula/ombro",
        "2",
        "15",
        "15-30 seg",
        "Ativar escapulas antes das puxadas e remadas.",
      ),
      ex(
        "Puxada alta pronada ou neutra no cross",
        "4",
        "8 a 12",
        "90 seg",
        "Peito aberto, cotovelos descem para as costelas.",
      ),
      ex(
        "Remada curvada com barra pronada",
        "4",
        "6 a 10",
        "2 min",
        "Base pesada. Coluna neutra, abdomen firme, cotovelo para tras.",
      ),
      ex(
        "Remada unilateral no cross ou halter",
        "3",
        "10 a 12 por lado",
        "90 seg",
        "Controlar a escapula. 1 seg de contracao no fim.",
      ),
      ex(
        "Puxada alta supinada no cross",
        "3",
        "8 a 12",
        "90 seg",
        "Puxar com cotovelo para baixo. Sem jogar o tronco para tras.",
      ),
      ex(
        "Pulldown com corda ou barra reta",
        "3",
        "12 a 15",
        "60-90 seg",
        "Bracos quase estendidos. Puxar para baixo e para tras.",
      ),
      ex(
        "Crucifixo invertido no cross ou banco inclinado",
        "3",
        "12 a 20",
        "60 seg",
        "Posterior de ombro e parte alta das costas. Sem encolher trapezio.",
      ),
      ex(
        "Lombar no banco inclinado ou superman",
        "2",
        "12 a 15",
        "60 seg",
        "Moderado. Nao destruir lombar antes do stiff pesado.",
      ),
    ],
  },
  {
    id: "dia-3",
    name: "Dia 3 - Peito",
    focus: "Peito principal",
    goal: "Prioridade em supino inclinado/reto com progressao real.",
    exercises: [
      ex(
        "Alongamento peitoral menor",
        "1-2",
        "20 seg",
        "curto",
        "Soltar ombro e peitoral antes de supinar.",
      ),
      ex(
        "Supino inclinado com barra ou halteres",
        "4",
        "6 a 10",
        "2 min",
        "Principal do peito. Use o suporte de seguranca. Progredir carga/reps quando der.",
      ),
      ex(
        "Supino reto com barra ou halteres",
        "3",
        "8 a 12",
        "90-120 seg",
        "Escapulas firmes no banco. Descer controlando, subir forte. 1-2 RIR.",
      ),
      ex(
        "Crucifixo inclinado no cross",
        "3",
        "10 a 15",
        "60-90 seg",
        "Alongar bem sem perder controle. Cotovelos semi-flexionados.",
      ),
      ex(
        "Crossover alto para baixo",
        "3",
        "12 a 15",
        "60 seg",
        "1 seg contraindo. Nao deixar ombro roubar.",
      ),
      ex(
        "Flexao no chao ou maos no step",
        "2",
        "quase falha",
        "60 seg",
        "Parar quando a tecnica cair.",
      ),
      ex(
        "Abdominal no cross",
        "3",
        "12 a 15",
        "60 seg",
        "Contrair abdomen, nao puxar so com braco/pescoco.",
      ),
    ],
  },
  {
    id: "dia-4",
    name: "Dia 4 - Posterior",
    focus: "Posterior e gluteo",
    goal: "Dobradica pesada, flexao de joelho improvisada e gluteo forte.",
    exercises: [
      ex(
        "Mobilidade leve gluteo/posterior",
        "2",
        "20 seg",
        "15-30 seg",
        "Soltar sem alongar demais.",
      ),
      ex(
        "Stiff / terra romeno com barra",
        "4",
        "6 a 10",
        "2-3 min",
        "Principal do posterior. Quadril para tras, barra perto da perna, coluna neutra.",
      ),
      ex(
        "Flexor deitado com halter no banco",
        "4",
        "10 a 15",
        "60-90 seg",
        "Halter preso entre os pes. 1 seg no topo, descida lenta.",
      ),
      ex(
        "Elevacao pelvica com barra",
        "4",
        "8 a 12",
        "90-120 seg",
        "2 seg de contracao no topo. Queixo recolhido. Nao hiperestender lombar.",
      ),
      ex(
        "Flexor unilateral em pe no cross/caneleira",
        "3",
        "12 a 15 por perna",
        "60 seg",
        "Quadril parado. Corrigir diferenca entre pernas.",
      ),
      ex(
        "Pull-through no cross",
        "3",
        "12 a 15",
        "60-90 seg",
        "Dobrar o quadril. Sentir gluteo/posterior, nao lombar.",
      ),
      ex(
        "Adutor no cross/caneleira",
        "3",
        "15 a 20 por perna",
        "45-60 seg",
        "Controle e amplitude.",
      ),
      ex(
        "Panturrilha sentada improvisada",
        "4",
        "12 a 20",
        "60 seg",
        "Anilha ou halter sobre o joelho, pe no step. Amplitude maxima.",
      ),
    ],
  },
  {
    id: "dia-5",
    name: "Dia 5 - Ombro",
    focus: "Deltoide lateral e posterior",
    goal: "Ombros fortes sem exagerar deltoide anterior.",
    exercises: [
      ex(
        "Mobilidade escapula/ombro",
        "2",
        "15",
        "15-30 seg",
        "Preparar articulacao antes de desenvolvimento e elevacoes.",
      ),
      ex(
        "Desenvolvimento sentado com halteres ou barra",
        "4",
        "6 a 10",
        "2 min",
        "Base do treino. Nao falhar. Punho alinhado, abdomen firme.",
      ),
      ex(
        "Elevacao lateral unilateral no cross",
        "4",
        "10 a 15",
        "60-90 seg",
        "Prioridade visual. Cotovelo guia o movimento.",
      ),
      ex(
        "Elevacao lateral com halteres",
        "3",
        "12 a 20",
        "60 seg",
        "Sem embalar. Nao precisa subir acima da linha do ombro.",
      ),
      ex(
        "Crucifixo invertido no banco inclinado ou cross",
        "4",
        "12 a 20",
        "60-90 seg",
        "Posterior de ombro. Maos e cotovelos na linha do ombro.",
      ),
      ex(
        "Face pull com corda",
        "3",
        "12 a 20",
        "60 seg",
        "Puxar para a altura do rosto. Cotovelos abertos.",
      ),
      ex(
        "Rotacao externa no cross",
        "2",
        "15 a 20",
        "45-60 seg",
        "Saude do ombro. Leve e limpo.",
      ),
    ],
  },
  {
    id: "dia-6",
    name: "Dia 6 - Peito + Bracos",
    focus: "Peito extra e bracos",
    goal: "Segundo estimulo de peito e bracos completos sem volume inutil.",
    exercises: [
      ex(
        "Supino inclinado leve/moderado",
        "3",
        "8 a 12",
        "90 seg",
        "Segundo estimulo da semana. Fazer com 2 RIR, foco em tecnica.",
      ),
      ex(
        "Crossover no cross",
        "2",
        "12 a 15",
        "60 seg",
        "Pump e contracao. Nao transformar em treino pesado de ombro.",
      ),
      ex(
        "Triceps supinado no cross ou supino fechado",
        "3",
        "6 a 10",
        "90-120 seg",
        "Exercicio pesado de triceps. Progredir com cotovelo saudavel.",
      ),
      ex(
        "Rosca direta com barra W",
        "3",
        "6 a 10",
        "90 seg",
        "Base do biceps. Sem roubar com lombar.",
      ),
      ex(
        "Triceps testa com barra W ou corda",
        "3",
        "8 a 12",
        "90 seg",
        "Cabeca longa do triceps. Cotovelos controlados.",
      ),
      ex(
        "Rosca inclinada com halteres",
        "3",
        "8 a 12",
        "90 seg",
        "Alongamento do biceps. Descida lenta.",
      ),
      ex(
        "Triceps corda/barra no cross",
        "2",
        "12 a 15",
        "60-90 seg",
        "Finalizador. 1 seg de contracao embaixo.",
      ),
      ex(
        "Rosca martelo com halteres ou corda",
        "2",
        "10 a 15",
        "60-90 seg",
        "Braquial e antebraco. Punho neutro.",
      ),
      ex(
        "Abdomen: prancha ou crunch declinado",
        "3",
        "45-60 seg ou 12-15",
        "60 seg",
        "Opcional. Fazer no final.",
      ),
    ],
  },
  {
    id: "dia-7",
    name: "Dia 7 - Descanso",
    focus: "Cardio leve",
    goal: "Caminhada ou corrida leve. Nao destruir perna entre os treinos.",
    exercises: [
      ex("Cardio leve", "1", "20 a 40 min", "leve", "Manter confortavel."),
    ],
  },
];

function ex(name, sets, reps, rest, notes) {
  return {
    id: name
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, ""),
    name,
    sets,
    reps,
    rest,
    notes,
  };
}
if (typeof module !== "undefined") module.exports = defaultPlan;
else window.DEFAULT_PLAN = defaultPlan;
